# Generated by Django 6.0.5 on 2026-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='fixado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ideia',
            name='tipo',
            field=models.CharField(choices=[('ideia', 'Ideia'), ('insight', 'Insight'), ('tarefa', 'Tarefa'), ('pergunta', 'Pergunta'), ('reflexao', 'Reflexão')], default='ideia', max_length=20),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='tags',
            field=models.CharField(blank=True, help_text='Separadas por vírgula', max_length=200),
        ),
    ]
