# Generated by Django 6.0.5 on 2026-05-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ideia_fixado_ideia_tipo_alter_ideia_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='jardim_midia/'),
        ),
    ]
