# Generated by Django 6.0.7 on 2026-07-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideia',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='cards_documentos/'),
        ),
        migrations.AlterField(
            model_name='ideia',
            name='tipo',
            field=models.CharField(choices=[('ideia', 'Ideia'), ('insight', 'Insight'), ('tarefa', 'Tarefa'), ('pergunta', 'Pergunta'), ('reflexao', 'Reflexão'), ('texto', 'Texto Simples'), ('markdown', 'Markdown'), ('arquivo', 'Documento/Planilha')], default='ideia', max_length=20),
        ),
    ]
