# Generated by Django 6.0.7 on 2026-07-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ideia_arquivo_alter_ideia_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideia',
            name='arquivo',
        ),
        migrations.CreateModel(
            name='ArquivoIdeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='cards_documentos/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('ideia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='core.ideia')),
            ],
        ),
    ]
