# Generated by Django 6.0.7 on 2026-07-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ideia_arquivo_arquivoideia'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivoideia',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to='cards_miniaturas/'),
        ),
    ]
